### ISSUE TITLE
感觉有一丝需要改动的地方

### ISSUE THREAD

**Issue by akkuman** [boy-hack/w13scan#1]
您的主体代码我大致上看了下，代码写得很棒，我从中学到了不少组织代码结构的思路，但是有一个地方我觉得有改进的空间，不知道我说的是否正确。

在看代码的时候，我始终有一个疑惑，这个入口点在哪，并不是指程序的入口点，是请求进来后，是在哪拦截的，loader插件是把所有的插件怼上去，但是从哪进 loader，我大致上看了一遍后并没有找到，然后我在 https://github.com/boy-hack/w13scan/blob/master/lib/baseproxy.py#L460 发现了，是从这进来的，觉得这一处放置的位置并不是太合理，我更倾向于应该移动到主体代码中去，这样结构上会更明晰

**Comment by akkuman** [comment]
看了下BaseProxy魔改后好像已经紧耦合在一起了

**Comment by boy-hack** [comment]
1.  因为loader模块要做的工作太多了才单独独立为插件，并且现在能在插件中调用插件运行了，这在后面会很有用，我不认为这个结构不清晰。

2. 虽然魔改了BaseProxy，但依然保留了它的独立性（除了你说的这个点https://github.com/boy-hack/w13scan/blob/master/lib/baseproxy.py#L460 但不得不这样做）

**Comment by akkuman** [comment]
明白了，我也是就感觉这一个位置，昨天看了下，也不知道怎么合适地脱出来




------------------ 原始邮件 ------------------
发件人: "boyhack"<notifications@github.com>; 
发送时间: 2019年7月10日(星期三) 上午10:08
收件人: "boy-hack/w13scan"<w13scan@noreply.github.com>; 
抄送: "Akkuman"<1075768094@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [boy-hack/w13scan] 感觉有一丝需要改动的地方 (#1)



 
 
因为loader模块要做的工作太多了才单独独立为插件，并且现在能在插件中调用插件运行了，这在后面会很有用，我不认为这个结构不清晰。
 
 
 
虽然魔改了BaseProxy，但依然保留了它的独立性（除了你说的这个点https://github.com/boy-hack/w13scan/blob/master/lib/baseproxy.py#L460 但不得不这样做）
