### ISSUE TITLE
无法扫描https

### ISSUE THREAD

**Issue by qiji2018** [boy-hack/w13scan#118]
下载证书且信任后，依旧无法对https网站进行扫描
![image](https://user-images.githubusercontent.com/38640195/64487534-6d177480-d26e-11e9-8ed3-c08f59a3c24a.png)
![Uploading image.png…]()

**Comment by boy-hack** [comment]
什么浏览器？返回什么提示？是一个网站如此（什么网站），还是所有https都不能（如果这种情况，一定是你自己的问题）

**Comment by qiji2018** [comment]
google浏览器
![image](https://user-images.githubusercontent.com/38640195/64529842-5cceca80-d33e-11e9-8fea-45ad328e29a4.png)
所有https都不行

**Comment by babaloveyou** [comment]
![image](https://user-images.githubusercontent.com/1131078/64934761-9e500000-d87f-11e9-9f11-4a6dac5f773a.png)

**Comment by babaloveyou** [comment]
火狐的提示

**Comment by babaloveyou** [comment]
![image](https://user-images.githubusercontent.com/1131078/64934776-b32c9380-d87f-11e9-919e-a912d7b137e0.png)
edge的提示,同样的网站burpsuite是可以打开的,怀疑证书有什么问题

**Comment by babaloveyou** [comment]
有些https可以打开有的不可以打开比如https://www.yitutech.com/这个就打不开

**Comment by babaloveyou** [comment]
建议建个微信群,可以讨论技术,提交问题

**Comment by boy-hack** [comment]
好的，我会在进行一些调试，之前的项目尝试过建群沟通，但效果都不太好，issue区是最好的渠道，也可以方便后来人查找问题

> 建议建个微信群,可以讨论技术,提交问题

**Comment by boy-hack** [comment]
没有后续的回复，所以关闭了

**Comment by babaloveyou** [comment]
修复这个问题了吗

**Comment by ldbfpiaoran** [comment]
@babaloveyou  pysocks 进行 http 代理时， 使用的是 HTTP CONNECT 方式， 对于不支持 CONNECT 方式的代理服务器，比如BurpSuite, 就无效

requests 进行 http 代理，不使用 HTTP CONNECT 方式， 兼容性更好

**Comment by haleibentengf4** [comment]
> 修复这个问题了吗
如果看到的话可以联系微信17621326763，打扰非常抱歉
