### ISSUE TITLE
登录类型网站登入后马上退出

### ISSUE THREAD

**Issue by tmprecorder** [boy-hack/w13scan#132]
你好，我用pip3 install安装，然后导入下载的download.crt证书，每次代理后，登录类的网站都会登录成功，但是马上退出重新要求登录，不用代理没问题，好几个网站都这个样子，不登陆的网站没关系。
我用的浏览器是firefox 69.0 (64-bit) for linux

**Comment by boy-hack** [comment]
w13scan会自动对当前页面的链接进行检测，内置一些链接如`logout`之类的是不会检测，可能网站的注销url不是这个。

解决办法：
- `w13scan --no-active`将不会使用功能

如果可以的化可以把链接的path部分贴出来吗，我加入到特征库中

**Comment by tmprecorder** [comment]
你是要logout的PATH部分还是？

**Comment by boy-hack** [comment]
`w13scan -h`查看帮助，或修改config.py里面的内容

**Comment by tmprecorder** [comment]
好的。谢谢。有没有联系方式方便进一步沟通测试。
