### ISSUE TITLE
不扫描规则

### ISSUE THREAD

**Issue by hackxx** [boy-hack/w13scan#151]
*/delete*,*logout*,*loginout*,*signout*,*logoff*,*signoff*,*exit*,*quit*,*byebye*,*bye-bye*,*clearuser*,*invalidate*,*security.php*,*reboot*,*shutdown*

**Comment by hackxx** [comment]
删,移除,停止,清空,注销,退出,再见,清除,重启,重载,无效,delete,remove,stop,undeploy,reload,restart,logout,signout,logoff,signoff,exit,quit,byebye,bye-bye,clearuser,invalidate

**Comment by boy-hack** [comment]
nice!
