### ISSUE TITLE
python新手的一个小问题

### ISSUE THREAD

**Issue by ontheway0101** [boy-hack/w13scan#5]
请问 [https://github.com/boy-hack/w13scan/blob/master/lib/controller.py#L80](https://github.com/boy-hack/w13scan/blob/master/lib/controller.py#L80) 中的 `KB["task_queue"]` 是什么时候 put 进去值的？

我 debug 时，访问一个 url 之后 `KB["task_queue"]` 中就有值了，我实在找不到是怎么放到队列中的，希望作者解答一下，谢谢。

还有就是 KB 这个字典是什么单词的缩写啊 Orz

**Comment by boy-hack** [comment]
1. 在代理框架`proxybase`中放入的，https://github.com/boy-hack/w13scan/blob/master/lib/baseproxy.py#L472 #1 有相同的问题，这么做可能看起来不太合理。。
2. KB最早看到是在sqlmap中，全称为KnowledgeBase，后面pocsuite3也用到过，在w13scan里面，kb相当于一个把所有全局变量"归到"一个字典中把。

**Comment by ontheway0101** [comment]
多谢大佬指点！！

`KB["task_queue"]`，`KB['task_queue']` 是我搜索关键字选的有点问题，早知道直接搜 `task_queue` 就好了！！

不过这代码规范还是统一一下比较好，对我这种菜鸡会更加友好一点～

------

在 `BaseProxy` 中加入队列这个问题，感觉是被多线程扫描、插件初始化的实现方式限制了，不知道有没有其他更好的实现方式。
