### ISSUE TITLE
默认配置的level0是怎么理解的？

### ISSUE THREAD

**Issue by littleheary** [boy-hack/w13scan#8]
请问，我看到config.py中level>=1加载部分插件，默认配置是level0，请问level0会加载哪些插件？其他的2-5分别会怎么工作？在哪个文件里有描述？我找了一下，没找到。

**Comment by boy-hack** [comment]
```
LEVEL = 0  # 根据检测深度由浅入深分为1～5级别，级别越高使用插件越多。
```
通过level定义等级来控制使用的插件，目前只完成了level 1等级，其他还未完善，level0表示不使用，即默认使用全部插件

**Comment by littleheary** [comment]
明白了，谢谢大佬。
